/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        xl: 'calc(var(--radius) * 4.5)',
        lg: 'calc(var(--radius) * 2)' ,
        md: 'var(--radius)',
        sm: 'calc(var(--radius) / 2)'
      },
      fontSize: {
        xs: '0.9285714rem',
        sm: '0.92857143rem',
        base: '1rem',
        lg: '1.14285714rem',
        xl: '1.28571429rem',
        '2xl': '1.42857143rem',
        '3xl': '1.71428571rem',
        '4xl': '2.14285714rem',
        '5xl': '2.5714286rem',
        '6xl': '2.8571429rem',
        '7xl': '3.4285714rem',
      },
      lineHeight: {
        xs: '0.8rem',
        sm: '0.9rem',
        base: '1rem',
        lg: '1.2rem',
        xl: '1.4rem',
        '2xl': '1.2rem',
        '3xl': '1.6rem',
        '4xl': '1.8rem',
        '5xl': '2rem',
        '6xl': '2.4rem',
        '7xl': '2.8rem',
      },
      fontWeight: {
        semibold: '600',
        normal: '400',
        medium: '500',
      },
      colors: {
        // shadcn-related colors
        'background': 'hsl(var(--background))',
        'foreground': 'hsl(var(--foreground))',
        'muted': 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        'card': 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        'popover': 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        'border': 'hsl(var(--border))',
        'input': 'hsl(var(--input))',
        'primary': 'rgb(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        'secondary': 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        'accent': 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        'destructive': 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        'ring': 'hsl(var(--ring))',

        // design-related colors
        'basic-black': 'rgb(var(--basic-black))',
        'basic-blue': 'rgb(var(--basic-blue))',
        'basic-white': 'rgb(var(--basic-white))',
        'basic-grey': 'rgb(var(--basic-grey))',

        'brand-900': 'rgb(var(--brand-900))',
        'brand-800': 'rgb(var(--brand-800))',
        'brand-700': 'rgb(var(--brand-700))',
        'brand-600': 'rgb(var(--brand-600))',
        'brand-500': 'rgb(var(--brand-500))',
        'brand-400': 'rgb(var(--brand-400))',
        'brand-300': 'rgb(var(--brand-300))',
        'brand-200': 'rgb(var(--brand-200))',
        'brand-100': 'rgb(var(--brand-100))',
        'brand-00': 'rgb(var(--brand-00))',

        'neutral-divider': 'rgb(var(--neutral-divider))',
        'neutral-900': 'rgb(var(--neutral-900))',
        'neutral-800': 'rgb(var(--neutral-800))',
        'neutral-700': 'rgb(var(--neutral-700))',
        'neutral-600': 'rgb(var(--neutral-600))',
        'neutral-500': 'rgb(var(--neutral-500))',
        'neutral-400': 'rgb(var(--neutral-400))',
        'neutral-300': 'rgb(var(--neutral-300))',
        'neutral-200': 'rgb(var(--neutral-200))',
        'neutral-100': 'rgb(var(--neutral-100))',
        'neutral-50': 'rgb(var(--neutral-50))',

        'status-danger-300': 'rgb(var(--status-danger-300))',
        'status-danger-200': 'rgb(var(--status-danger-200))',
        'status-danger-100': 'rgb(var(--status-danger-100))',
        'status-warning-300': 'rgb(var(--status-warning-300))',
        'status-warning-200': 'rgb(var(--status-warning-200))',
        'status-warning-100': 'rgb(var(--status-warning-100))',
        'status-success-300': 'rgb(var(--status-success-300))',
        'status-success-200': 'rgb(var(--status-success-200))',
        'status-success-100': 'rgb(var(--status-success-100))',

        'other-purple': 'rgb(var(--other-purple))',
        'other-purple-10': 'rgba(var(--other-purple-10))',
        'other-red': 'rgb(var(--other-red))',
        'other-red-10': 'rgba(var(--other-red-10))',
        'other-orange': 'rgb(var(--other-orange))',
        'other-orange-10': 'rgba(var(--other-orange-10))',
        'other-blue': 'rgb(var(--other-blue))',
        'other-blue-10': 'rgba(var(--other-blue-10))',
      },
    }
  },
  plugins: [require("tailwindcss-animate")],
}

