import { Module } from '@/types/module';
import { ProfileArea } from '@/types/enums/profile-area';

export const MODULES: Module[] = [
  { name: 'contacts', isExternal: true },
  { name: 'msg', isExternal: true },
  { name: 'kurator', isExternal: true },
  { name: 'rnp', isExternal: true },
  { name: 'vote', isExternal: true },
  { name: 'studysheet', isExternal: (profileArea: ProfileArea) => profileArea === ProfileArea.Employee },
  { name: 'rectorialcontrol', isExternal: true },
  { name: 'vedomoststud', isExternal: false },
  { name: 'pk2024', isExternal: true },
  { name: 'studdoc', isExternal: true },
  { name: 'plans_individual', isExternal: true },
  { name: 'journals', isExternal: true },
  { name: 'np', isExternal: true },
  { name: 'lists', isExternal: true },
  { name: 'sessiyaNPP', isExternal: true },
  { name: 'plans', isExternal: true },
  { name: 'attestation', isExternal: true },
  { name: 'vedomost', isExternal: true },
  { name: 'vidpovidalniy', isExternal: true },
  { name: 'reytinghelp', isExternal: true },
  { name: 'ratingnpp', isExternal: true, group: 'rating' },
  { name: 'ratingnpp2021', isExternal: true, group: 'rating' },
  { name: 'ratingnpp2022', isExternal: true, group: 'rating' },
  { name: 'ratingnpp2023', isExternal: true, group: 'rating' },
  { name: 'ratingnpp2024', isExternal: true, group: 'rating' },
  { name: 'webometrics', isExternal: true },
  { name: 'attestationresults', isExternal: true },
  { name: 'ekanat', isExternal: true },
  { name: 'editRNP', isExternal: true },
  { name: 'hignyak', isExternal: true },
  { name: 'rnpedit', isExternal: true },
  { name: 'rnpupd', isExternal: true },
  { name: 'rnpupd2', isExternal: true },
  { name: 'voteresult', isExternal: true },
  { name: 'vedomostadmin', isExternal: true },
  { name: 'zvit', isExternal: true },
  { name: 'zamdekan', isExternal: true },
  { name: 'zavkaf', isExternal: true },
  { name: 'zdekan', isExternal: true },
  { name: 'ekk', isExternal: true },
  { name: 'bravook', isExternal: true },
  { name: 'pk2024admin', isExternal: true },
  { name: 'studdocadmin', isExternal: true },
  { name: 'yiystat', isExternal: true },
  { name: 'adminpanel', isExternal: true },
  { name: 'sdchoice2021admin', isExternal: true },
  { name: 'sdchoice2021moderator', isExternal: true },
  { name: 'sdchoice2021nmv', isExternal: true },
  { name: 'mob', isExternal: true },
  { name: 'employment', isExternal: false },
  { name: 'useract', isExternal: true },
];
