function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function createMockPdf(reportId: string) {
  const lines = [
    'K-7 report preview',
    `Report id: ${reportId}`,
    'This is a mock PDF generated by the preview endpoint.',
  ];
  const content = [
    'BT',
    '/F1 16 Tf',
    '72 760 Td',
    ...lines.flatMap((line, index) => [index === 0 ? '' : '0 -24 Td', `(${escapePdfText(line)}) Tj`]),
    'ET',
  ]
    .filter(Boolean)
    .join('\n');
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj',
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
    `5 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj`,
  ];
  const header = '%PDF-1.4\n';
  const offsets: number[] = [];
  let body = '';

  for (const object of objects) {
    offsets.push(header.length + body.length);
    body += `${object}\n`;
  }

  const xrefOffset = header.length + body.length;
  const xrefRows = offsets.map((offset) => `${offset.toString().padStart(10, '0')} 00000 n \n`).join('');
  const trailer = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${xrefRows}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return new TextEncoder().encode(header + body + trailer);
}

export async function GET(_request: Request, { params }: { params: Promise<{ reportId: string }> }) {
  const { reportId } = await params;
  const pdf = createMockPdf(reportId);

  return new Response(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="k-7-${reportId}.pdf"`,
      'Content-Length': pdf.byteLength.toString(),
    },
  });
}
