<%@ Page Title="ОПП ГСВО" Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Default.aspx.cs" Inherits="Site.Modules.SubSystems.GSVO.Default" %>

<asp:Content ID="breadcrumbs_content" ContentPlaceHolderID="breadcrumbs" runat="server">
    <li><a href="/Default.aspx">Домашня</a></li>
    <li><a href="../Default.aspx">Вибір підсистеми</a></li>
    <li class="active">ОПП ГСВО</li>
</asp:Content>

<asp:Content ID="body_content" ContentPlaceHolderID="body" runat="server">
    <div class="page-header">
        <h1><%-- <center>
        <span>Оберіть кафедру</span>
        <asp:DropDownList ID="SList" runat="server" class="form-control" placeholder="Почніть вводити назву кафедри" AutoPostBack="true" width="700"></asp:DropDownList>
    </center>--%></h1>
        <h3>Освітньо-професійна програма - Галузевий стандарт вищої освіти</h3>
    </div>
    
   <%-- <center>
        <span>Оберіть кафедру</span>
        <asp:DropDownList ID="SList" runat="server" class="form-control" placeholder="Почніть вводити назву кафедри" AutoPostBack="true" width="700"></asp:DropDownList>
    </center>--%>
    <span id="NameDisc" runat="server" class="input-group-addon col-md-3" style="padding: 9px 9px; width: 235px">Оберіть кафедру</span>
    <div class="input-group col-md-9">
        <asp:DropDownList ID="CafList" runat="server" class="form-control" placeholder="Почніть вводити назву кафедри" AutoPostBack="true" OnLoad="CafList_Load" OnSelectedIndexChanged="CafList_SelectedIndexChanged"></asp:DropDownList>
    </div>
    
    <div class="main-block">
        <asp:TreeView ID="TreeView" runat="server" ExpandDepth="0" Width="100%" AutoGenerateDataBindings="False" ImageSet="Arrows" Height="322px" OnLoad="TreeView_Load" OnSelectedNodeChanged="TreeView_SelectedNodeChanged">
            <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
            <NodeStyle ForeColor="Black" Font-Names="Tahoma" Font-Size="10pt" HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" />
            <ParentNodeStyle Font-Bold="False" />
            <RootNodeStyle ForeColor="Black" />
            <SelectedNodeStyle ForeColor="#5555DD" Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
        </asp:TreeView>
    </div>         
</asp:Content>