name: Build PR ecampus.kpi.ua

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - dev

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
